[package]
name = "sport_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.15.4"
axum = "0.8.8"
tokio = { version = "1.36.0", features = ["full"] }
chrono = "0.4.43"
serde = { version = "1.0.228", features = ["derive"] }
serde_yml = "0.0.12"
